In [1]:
[i for i in zip([1,2,3],[4,5,6],[7,8,9])]

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [9]:
import torch
import torch.nn as nn

# 假设有一个 2 行 20 列的数据
input_data = torch.randn(1, 2, 20)

# 定义一维卷积层
input_channels = 2
output_channels = 1  # 输出为一行
kernel_size = 5
stride = 1

conv1d_layer = nn.Conv1d(in_channels=input_channels, out_channels=output_channels, kernel_size=kernel_size, stride=stride,padding=2)

# 前向传播
output_data = conv1d_layer(input_data)

# 将输出的维度调整为一行
output_data = output_data

# 打印输入和输出的形状
print("Input shape:", input_data.shape)
print("Output shape:", output_data.shape)


Input shape: torch.Size([1, 2, 20])
Output shape: torch.Size([1, 1, 20])


In [10]:
torch.randint(1, 1000, (20,))

tensor([930, 638, 312, 515, 155, 189, 507,  73, 214, 637, 281, 584, 725, 339,
        276, 180, 716,  94, 326, 931])

: 

In [13]:
import torch
t = torch.tensor([[[1,1,1],[2,2,2]]], dtype=torch.float32)
conv = torch.nn.Conv1d(kernel_size=1,in_channels=2,out_channels=2)
conv.weight = torch.nn.Parameter(torch.FloatTensor([[[0.1],[ 0.2]],[[ 0.3],[ 0.4]]]), requires_grad = True)
print(conv.weight)
print(conv(t))
print(t.transpose(-1, -2).transpose(-1, -2))

Parameter containing:
tensor([[[0.1000],
         [0.2000]],

        [[0.3000],
         [0.4000]]], requires_grad=True)
tensor([[[0.0841, 0.0841, 0.0841],
         [0.6667, 0.6667, 0.6667]]], grad_fn=<ConvolutionBackward0>)
tensor([[[1., 1., 1.],
         [2., 2., 2.]]])


In [3]:
'ssadas'.isalpha()

True

In [9]:
import re

def process_strings(input_list):
    result_list = []

    for sublist in input_list:
        sentence = ""
        for i, s in enumerate(sublist):
            if i > 0:
                # 如果前一个字符串是中文，当前字符串是英文，加一个空格
                if sublist[i-1].encode("utf-8").isalpha() and s.encode("utf-8").isalpha():
                    sentence += " "
            sentence += s

        result_list.append(sentence)

    return result_list

# 例子
input_list = [["Hello", "你好", "World", "yes", "世界"], ["Python", "是", "Great"]]
result = process_strings(input_list)

for sentence in result:
    print(sentence)


Hello你好World yes世界
Python是Great


In [8]:
"a".encode("utf-8").isalpha()

True

In [41]:
t = torch.randn((4,2,20))
t = torch.tensor([[[1,2,3],[1,2,3]], [[4,5,6],[4,5,6]], [[4,5,6],[4,5,6]]],dtype=torch.float32)
t.shape

torch.Size([3, 2, 3])

In [54]:
a = t.transpose(-1,-2)
a,a.shape

(tensor([[[1., 1.],
          [2., 2.],
          [3., 3.]],
 
         [[4., 4.],
          [5., 5.],
          [6., 6.]],
 
         [[4., 4.],
          [5., 5.],
          [6., 6.]]]),
 torch.Size([3, 3, 2]))

In [52]:
conv1d_layer = torch.nn.Conv1d(in_channels=2, out_channels=5, kernel_size=1, stride=1, padding=0)
conv1d_layer.weight,t,conv1d_layer.weight.shape


(Parameter containing:
 tensor([[[-0.1646],
          [ 0.6534]],
 
         [[ 0.1090],
          [-0.4285]],
 
         [[-0.3015],
          [ 0.2379]],
 
         [[-0.6495],
          [-0.7012]],
 
         [[ 0.3790],
          [-0.2901]]], requires_grad=True),
 tensor([[[1., 2., 3.],
          [1., 2., 3.]],
 
         [[4., 5., 6.],
          [4., 5., 6.]],
 
         [[4., 5., 6.],
          [4., 5., 6.]]]),
 torch.Size([5, 2, 1]))

In [60]:
conv1d_layer(t).transpose(-1,-2),conv1d_layer(t),conv1d_layer(t).shape

(tensor([[[-8.2144e-02, -5.3952e-01,  3.5797e-01, -1.8344e+00, -3.4910e-01],
          [ 4.0671e-01, -8.5906e-01,  2.9433e-01, -3.1851e+00, -2.6020e-01],
          [ 8.9556e-01, -1.1786e+00,  2.3069e-01, -4.5358e+00, -1.7130e-01]],
 
         [[ 1.3844e+00, -1.4981e+00,  1.6705e-01, -5.8865e+00, -8.2404e-02],
          [ 1.8733e+00, -1.8177e+00,  1.0341e-01, -7.2372e+00,  6.4942e-03],
          [ 2.3621e+00, -2.1372e+00,  3.9772e-02, -8.5879e+00,  9.5392e-02]],
 
         [[ 1.3844e+00, -1.4981e+00,  1.6705e-01, -5.8865e+00, -8.2404e-02],
          [ 1.8733e+00, -1.8177e+00,  1.0341e-01, -7.2372e+00,  6.4942e-03],
          [ 2.3621e+00, -2.1372e+00,  3.9772e-02, -8.5879e+00,  9.5392e-02]]],
        grad_fn=<TransposeBackward0>),
 tensor([[[-8.2144e-02,  4.0671e-01,  8.9556e-01],
          [-5.3952e-01, -8.5906e-01, -1.1786e+00],
          [ 3.5797e-01,  2.9433e-01,  2.3069e-01],
          [-1.8344e+00, -3.1851e+00, -4.5358e+00],
          [-3.4910e-01, -2.6020e-01, -1.7130e-01]],
 
  

In [80]:
t = torch.tensor([[[1,2,3],[1,2,3]], [[4,5,6],[4,5,6]], [[4,5,6],[4,5,6]]],dtype=torch.float32)
_6 = torch.nn.Linear(3, 18)(t)
_6.chunk(3,dim=1)
# t.chunk(3,dim=1)

(tensor([[[ 0.7224,  0.1146, -0.9273, -2.0567,  2.1017, -0.9772, -2.1439,
           -1.7455,  0.3757,  0.4538,  0.5992,  0.2861, -1.1652, -1.9026,
            1.8405,  0.3783,  0.9165, -0.4001]],
 
         [[ 0.9042,  0.8730, -3.3975, -5.3596,  4.4408, -0.7968, -5.7718,
           -3.0951,  1.6366,  1.4351,  0.5190, -0.9379, -2.2598, -5.0389,
            2.5155,  0.8887,  2.9455, -1.6438]],
 
         [[ 0.9042,  0.8730, -3.3975, -5.3596,  4.4408, -0.7968, -5.7718,
           -3.0951,  1.6366,  1.4351,  0.5190, -0.9379, -2.2598, -5.0389,
            2.5155,  0.8887,  2.9455, -1.6438]]], grad_fn=<SplitBackward0>),
 tensor([[[ 0.7224,  0.1146, -0.9273, -2.0567,  2.1017, -0.9772, -2.1439,
           -1.7455,  0.3757,  0.4538,  0.5992,  0.2861, -1.1652, -1.9026,
            1.8405,  0.3783,  0.9165, -0.4001]],
 
         [[ 0.9042,  0.8730, -3.3975, -5.3596,  4.4408, -0.7968, -5.7718,
           -3.0951,  1.6366,  1.4351,  0.5190, -0.9379, -2.2598, -5.0389,
            2.5155,  0.8887,  

In [75]:
time = torch.tensor([[[1,1,1]], [[1,1,1]], [[1,1,1]]],dtype=torch.float32)
t + time

tensor([[[2., 3., 4.],
         [2., 3., 4.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [74]:
batch_outputs = []
print(t.shape)
batch_outputs.append(t)
batch_outputs.append(t)
torch.stack(batch_outputs).cuda(),torch.stack(batch_outputs).shape

torch.Size([3, 2, 3])


(tensor([[[[1., 2., 3.],
           [1., 2., 3.]],
 
          [[0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.]]],
 
 
         [[[1., 2., 3.],
           [1., 2., 3.]],
 
          [[0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.]]]], device='cuda:0'),
 torch.Size([2, 3, 2, 3]))

In [92]:
def ddpm_schedules(beta1, beta2, T):
    """
    Returns pre-computed schedules for DDPM sampling, training process.
    """
    assert beta1 < beta2 < 1.0, "beta1 and beta2 must be in (0, 1)"

    beta_t = (beta2 - beta1) * torch.arange(0, T + 1, dtype=torch.float32) / T + beta1
    sqrt_beta_t = torch.sqrt(beta_t)
    alpha_t = 1 - beta_t
    log_alpha_t = torch.log(alpha_t)
    alphabar_t = torch.cumsum(log_alpha_t, dim=0).exp()

    sqrtab = torch.sqrt(alphabar_t)
    oneover_sqrta = 1 / torch.sqrt(alpha_t)

    sqrtmab = torch.sqrt(1 - alphabar_t)
    mab_over_sqrtmab_inv = (1 - alpha_t) / sqrtmab
    test = torch.tensor([i for i in range(T + 1)])
    return {
        "alpha_t": alpha_t,  # \alpha_t
        "oneover_sqrta": oneover_sqrta,  # 1/\sqrt{\alpha_t}
        "sqrt_beta_t": sqrt_beta_t,  # \sqrt{\beta_t}
        "alphabar_t": alphabar_t,  # \bar{\alpha_t}
        "sqrtab": sqrtab,  # \sqrt{\bar{\alpha_t}}
        "sqrtmab": sqrtmab,  # \sqrt{1-\bar{\alpha_t}}
        "mab_over_sqrtmab": mab_over_sqrtmab_inv,  # (1-\alpha_t)/\sqrt{1-\bar{\alpha_t}}
        "test": test
    }
ddpm_schedules(0.002,0.003,6)

{'alpha_t': tensor([0.9980, 0.9978, 0.9977, 0.9975, 0.9973, 0.9972, 0.9970]),
 'oneover_sqrta': tensor([1.0010, 1.0011, 1.0012, 1.0013, 1.0013, 1.0014, 1.0015]),
 'sqrt_beta_t': tensor([0.0447, 0.0465, 0.0483, 0.0500, 0.0516, 0.0532, 0.0548]),
 'alphabar_t': tensor([0.9980, 0.9958, 0.9935, 0.9910, 0.9884, 0.9856, 0.9826]),
 'sqrtab': tensor([0.9990, 0.9979, 0.9968, 0.9955, 0.9942, 0.9928, 0.9913]),
 'sqrtmab': tensor([0.0447, 0.0645, 0.0805, 0.0947, 0.1078, 0.1201, 0.1318]),
 'mab_over_sqrtmab': tensor([0.0447, 0.0336, 0.0290, 0.0264, 0.0247, 0.0236, 0.0228]),
 'test': tensor([0, 1, 2, 3, 4, 5, 6])}

In [99]:
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        
        # 创建一个张量作为缓冲区，并注册为模型的一部分
        for k, v in ddpm_schedules(0.002, 0.003, 7).items():
            self.register_buffer(k, v)

# 创建模型实例
model = MyModel()

# 访问缓冲区
_ts = torch.tensor([1,3,5])
t = torch.tensor([[[1,2,3], [1,2,3]]])
buffer_value = model.test[_ts, None, None]
print(t.shape,buffer_value.shape)
print("Buffer Value:", buffer_value)

buffer_value * t,(buffer_value * t).shape


torch.Size([1, 2, 3]) torch.Size([3, 1, 1])
Buffer Value: tensor([[[1]],

        [[3]],

        [[5]]])


(tensor([[[ 1,  2,  3],
          [ 1,  2,  3]],
 
         [[ 3,  6,  9],
          [ 3,  6,  9]],
 
         [[ 5, 10, 15],
          [ 5, 10, 15]]]),
 torch.Size([3, 2, 3]))

In [6]:
import torch

t = torch.tensor([[1,2], [3,4]]).view(2, -1, 2).repeat(1, 5, 1)
print(t)
t.squeeze(0)

tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4],
         [3, 4]]])


tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4],
         [3, 4]]])

In [14]:
import torch

# 假设 data 是你的数据，一个 PyTorch 张量，形状为 (50, 20, 2)
data = torch.randn((50, 20, 2))

# 计算原始数据的均值和标准差
original_mean = data.mean(dim=(0, 1))
original_std = data.std(dim=(0, 1))

# 定义均值和标准差，可以根据实际情况设置
mean = torch.tensor([0.5, 0.5])
std = torch.tensor([0.5, 0.5])

# 使用标准化公式进行标准化
normalized_data = (data - mean) / std

# 计算标准化后数据的均值和标准差
normalized_mean = normalized_data.mean(dim=(0, 1))
normalized_std = normalized_data.std(dim=(0, 1))

print("原始数据的均值:", original_mean)
print("原始数据的标准差:", original_std)

print("标准化后数据的均值:", normalized_mean)
print("标准化后数据的标准差:", normalized_std)


原始数据的均值: tensor([-0.0289, -0.0131])
原始数据的标准差: tensor([0.9882, 0.9788])
标准化后数据的均值: tensor([-1.0578, -1.0262])
标准化后数据的标准差: tensor([1.9764, 1.9576])


In [6]:
from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]  
    
image.save("astronaut_rides_horse.png")


model_index.json:   0%|          | 0.00/541 [00:00<?, ?B/s]

d:\Anaconda3\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\lenovo\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Fetching 15 files:   0%|          | 0/15 [00:00<?, ?it/s]

(…)ature_extractor/preprocessor_config.json:   0%|          | 0.00/342 [00:00<?, ?B/s]

text_encoder/config.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

tokenizer/special_tokens_map.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

safety_checker/config.json:   0%|          | 0.00/4.72k [00:00<?, ?B/s]

scheduler/scheduler_config.json:   0%|          | 0.00/308 [00:00<?, ?B/s]

tokenizer/merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

d:\Anaconda3\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:992: UserWarning: Not enough free disk space to download the file. The expected file size is: 3438.17 MB. The target location C:\Users\lenovo\.cache\huggingface\hub only has 1792.57 MB free disk space.
  warnings.warn(
d:\Anaconda3\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:992: UserWarning: Not enough free disk space to download the file. The expected file size is: 3438.17 MB. The target location C:\Users\lenovo\.cache\huggingface\hub\models--runwayml--stable-diffusion-v1-5\blobs only has 1792.57 MB free disk space.
  warnings.warn(


model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/492M [00:00<?, ?B/s]

tokenizer/vocab.json:   0%|          | 0.00/1.06M [00:00<?, ?B/s]

unet/config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

tokenizer/tokenizer_config.json:   0%|          | 0.00/806 [00:00<?, ?B/s]

vae/config.json:   0%|          | 0.00/547 [00:00<?, ?B/s]

diffusion_pytorch_model.safetensors:   0%|          | 0.00/3.44G [00:00<?, ?B/s]

diffusion_pytorch_model.safetensors:   0%|          | 0.00/335M [00:00<?, ?B/s]

OSError: [Errno 28] No space left on device